version: '3.7'

services:
  vendorbot_service:
    environment:
      - PYTHONUNBUFFERED=1
      - MONGO_VENDORBOT_DATABASE=test_db
      - BOT_TOKEN=${BOT_TOKEN}
    restart: "no"
    command:  conda run -n vendorbot_env --no-capture-output pytest

  mongodb_api:
    restart: "no"

volumes:
    mongodb_api:
    mongo_dumps:
