name: Deploy development

on:
  push:
    branches:
    - dev

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - name: Docker-compose pytest
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DEVELOPMENT_HOST }}
        username: ${{ secrets.DEVELOPMENT_USERNAME }}
        key: ${{ secrets.DEVELOPMENT_SSHKEY }}
        script_stop: true
        script: |
          cd ./labaggregator2022-dev
          git checkout dev
          git pull

    - name: create env file
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DEVELOPMENT_HOST }}
        username: ${{ secrets.DEVELOPMENT_USERNAME }}
        key: ${{ secrets.DEVELOPMENT_SSHKEY }}
        script_stop: true
        script: |    # 1я переменная с >, остальные с >>
          cd ./labaggregator2022-dev
          touch .env
          echo BOT_TOKEN=${{ secrets.DEVELOPMENT_BOT_TOKEN }} > .env

    - name: Docker-compose pytest
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DEVELOPMENT_HOST }}
        username: ${{ secrets.DEVELOPMENT_USERNAME }}
        key: ${{ secrets.DEVELOPMENT_SSHKEY }}
        script_stop: true
        script: |
          cd ./labaggregator2022-dev
          docker-compose -f docker-compose.yml -f docker-compose.pytest.yml up --build --abort-on-container-exit

    - name: Docker-compose up
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DEVELOPMENT_HOST }}
        username: ${{ secrets.DEVELOPMENT_USERNAME }}
        key: ${{ secrets.DEVELOPMENT_SSHKEY }}
        script_stop: true
        script: |
          cd ./labaggregator2022-dev
          docker-compose up -d --build
          docker image prune -f